SearchedLinks = []
UnsearchedLinks = []
Chain1 = []
Chain2 = []
Pairs = [
	['*Thanksgiving*','Acadia National Park'],
	['Acadia National Park','Bald Eagle'],
	['Acadia National Park','Barcelona'],
	['Acadia National Park','Bhumibol Bridge'],
	['Acadia National Park','Cape Reinga'],
	['Acadia National Park','Chicago Dance'],
	['Acadia National Park','Four Corners Monument'],
	['Acadia National Park','Great Barrier Reef'],
	['Acadia National Park','Haystock Rock'],
	['Acadia National Park','Hurricane Katrina'],
	['Acadia National Park','Palace of Westminster'],
	['Acadia National Park','Texas'],
	['Acadia National Park','Thanksgiving'],
	['Acadia National Park','Triple Falls'],
	['Acadia National Park','Bald Eagle'],
	['Acadia National Park','Barcelona'],
	['Acadia National Park','Bhumibol Bridge'],
	['Acadia National Park','Blueberry'],
	['Acadia National Park','Cape Reinga'],
	['Acadia National Park','Caribbean'],
	['Acadia National Park','Chicago'],
	['Acadia National Park','Dance'],
	['Acadia National Park','Four Corners Monument'],
	['Acadia National Park','Great Barrier Reef'],
	['Acadia National Park','Haystock Rock'],
	['Acadia National Park','Hurrican Katrina'],
	['Acadia National Park','Italy'],
	['Acadia National Park','Palace of Westminster'],
	['Acadia National Park','Rabbit'],
	['Acadia National Park','Snack'],
	['Acadia National Park','Texas'],
	['Acadia National Park','*Thanksgiving*'],
	['Acadia National Park','Triple Falls'],
	['Acadia National Park','Bald Eagle'],
	['Acadia National Park','Barcelona'],
	['Acadia National Park','Bhumibol Bridge'],
	['Acadia National Park','Blueberry'],
	['Acadia National Park','Italy'],
	['Amazon Rainforest','Bartolome Island'],
	['Andalusia','Barcelona'],
	['Andalusia','Chess'],
	['Andalusia','Chicago'],
	['Andalusia','Dance'],
	['Andalusia','Grizzly Bear'],
	['Andalusia','Laguna Beach'],
	['Andalusia','Tarutao National Marine Park'],
	['Andalusia','Texas'],
	['Andalusia','Barcelona'],
	['Andalusia','Bearded Vulture'],
	['Andalusia','Chess'],
	['Andalusia','Chicago'],
	['Andalusia','Dance'],
	['Andalusia','Ice Cream'],
	['Andalusia','Laguna Beach'],
	['Andalusia','Lovebird'],
	['Andalusia','Snack'],
	['Andalusia','Tarutao National Marine Park'],
	['Andalusia','Texas'],
	['Andalusia','Triple Falls'],
	['Andalusia','Barcelona'],
	['Andalusia','Bearded Vulture'],
	['Arches National Park','Bald Eagle'],
	['Arches National Park','Barcelona'],
	['Arches National Park','Bearded Vulture'],
	['Arches National Park','Broccoli'],
	['Arches National Park','Chicago'],
	['Arches National Park','Four Corners Monument'],
	['Arches National Park','Junk Food'],
	['Arches National Park','Rabbit'],
	['Arches National Park','Snack'],
	['Arches National Park','Texas'],
	['Arches National Park','Bald Eagle'],
	['Arches National Park','Barcelona'],
	['Arches National Park','Bearded Valture'],
	['Arches National Park','Broccoli'],
	['Arches National Park','Butchart Gardens'],
	['Arches National Park','Chicago'],
	['Arches National Park','Drawing'],
	['Arches National Park','Four Corners Monument'],
	['Arches National Park','Junk Food'],
	['Arches National Park','Ketogenic'],
	['Arches National Park','Lung'],
	['Arches National Park','Rabbit'],
	['Arches National Park','Snack'],
	['Arches National Park','Texas'],
	['Arches National Park','Zucchini'],
	['Arches National Park','Bald Eagle'],
	['Arches National Park','Barcelona'],
	['Arches National Park','Bearded Vulture'],
	['Arches National Park','Broccoli'],
	['Arches National Park','Lung'],
	['Argania','Barcelona'],
	['Argania','Cape Reinga'],
	['Argania','Haystack Rock'],
	['Argania','Honolulu'],
	['Argania','Junk Food'],
	['Argania','Lovebird'],
	['Argania','Moon'],
	['Argania','Sailfish'],
	['Argania','Santa Catalina Island'],
	['Argania','Snack'],
	['Argania','Amazon Rainforest'],
	['Argania','Amazon Rain Forest'],
	['Argania','Barcelona'],
	['Argania','Bhumibol Bridge'],
	['Argania','Broccoli'],
	['Argania','Cape Reinga'],
	['Argania','Haystack Rock'],
	['Argania','Honolulu'],
	['Argania','Junk Food'],
	['Argania','Laguna Beach'],
	['Argania','Lovebird'],
	['Argania','Moon'],
	['Argania','Santa Catalina Island'],
	['Argania','Snack'],
	['Argania','Barcelona'],
	['Argania','Bhumibol Bridge'],
	['Argania','Broccoli'],
	['Avocado','Andalusia'],
	['Avocado','Arches National Park'],
	['Avocado','Bartolome Island'],
	['Avocado','Bernese Alps'],
	['Avocado','Corfe Castle'],
	['Avocado','Hippopotamus'],
	['Avocado','Maldives'],
	['Avocado','Memphis'],
	['Avocado','New York'],
	['Avocado','Ozark National Scenic Riverways'],
	['Avocado','Paddleboarding'],
	['Avocado','Palace of Fine Arts'],
	['Avocado','Pennybacker Bridge'],
	['Avocado','Rapa Valley'],
	['Avocado','Salt Spring Island'],
	['Avocado','Saskatchewan'],
	['Avocado','Swimming'],
	['Avocado','Volcano'],
	['Avocado','Andalusia'],
	['Avocado','Arches National Park'],
	['Avocado','Andalusia'],
	['Avocado','Arches National Park'],
	['Avocado','Bartolome Island'],
	['Avocado','Bernese Alps'],
	['Avocado','Corfe Castle'],
	['Avocado','Everglades National Park'],
	['Avocado','Hawaii'],
	['Avocado','Hippopotamus'],
	['Avocado','Krakatoa'],
	['Avocado','Maldives'],
	['Avocado','Memphis'],
	['Avocado','New York'],
	['Avocado','Ozark National Scenic Riverways'],
	['Avocado','Paddleboarding'],
	['Avocado','Palace of Fine Arts'],
	['Avocado','Pennybacker Bridge'],
	['Avocado','Rapa Valley'],
	['Avocado','Salt Spring Island'],
	['Avocado','Saskatchewan'],
	['Avocado','Swimming'],
	['Avocado','Volcano'],
	['Avocado','Bartolome Island'],
	['Avocado','Bernese Alps'],
	['Ayodhya','Toco Toucan'],
	['Bald Eagle','Hurricane Katrina'],
	['Bald Eagle','Nashville'],
	['Bald Eagle','Hurricane Katrina'],
	['Bald Eagle','Nashville'],
	['Bald Eagle','New York'],
	['Bald Eagle','Volcano'],
	['Barcelona','Sardinia'],
	['Barn Owl','Amazon Rainforest'],
	['Barn Owl','Barcelona'],
	['Barn Owl','Bhumibol Bridge'],
	['Barn Owl','Cabo San Lucas'],
	['Barn Owl','Dance'],
	['Barn Owl','Four Corners Monument'],
	['Barn Owl','French Fries'],
	['Barn Owl','Grasslands National Park'],
	['Barn Owl','Hurricane Katrina'],
	['Barn Owl','Lake Geneva'],
	['Barn Owl','Lake of the Clouds'],
	['Barn Owl','Los Angeles'],
	['Barn Owl','Moon'],
	['Barn Owl','Murlough Bay'],
	['Barn Owl','Palace of Fine Arts'],
	['Barn Owl','Pennybacker Bridge Similan Islands'],
	['Barn Owl','Toco Toucan'],
	['Barn Owl','Triple Falls'],
	['Barn Owl','Amazon Rainforest'],
	['Barn Owl','Barcelona'],
	['Barn Owl','Amazon Rainforest'],
	['Barn Owl','Barcelona'],
	['Barn Owl','Bhumibol Bridge'],
	['Barn Owl','Cabo San Lucas'],
	['Barn Owl','Dance'],
	['Barn Owl','Flamingo'],
	['Barn Owl','Four Corners Monument'],
	['Barn Owl','French Fries'],
	['Barn Owl','Grasslands National Park'],
	['Barn Owl','Honolulu'],
	['Barn Owl','Hurricane Katrina'],
	['Barn Owl','Lake Geneva'],
	['Barn Owl','Lake of the Clouds'],
	['Barn Owl','Los Angeles'],
	['Barn Owl','Manatee'],
	['Barn Owl','Moon'],
	['Barn Owl','Murlough Bay'],
	['Barn Owl','Palace of Fine Arts'],
	['Barn Owl','Pennybacker Bridge Similan Islands'],
	['Barn Owl','Snack'],
	['Barn Owl','Sun Moon Lake'],
	['Barn Owl','Toco Toucan'],
	['Barn Owl','Triple Falls'],
	['Barn Owl','Bhumibol Bridge'],
	['Bartolome Island','Bora Bora'],
	['Bartolome Island','Los Angeles'],
	['Bartolome Island','Memphis'],
	['Bartolome Island','Nashville'],
	['Bartolome Island','Snack'],
	['Bartolome Island','Tablespoon'],
	['Bartolome Island','Volcano'],
	['Bartolome Island','Bora Bora'],
	['Bartolome Island','Los Angeles'],
	['Bartolome Island','Memphis'],
	['Bartolome Island','Nashville'],
	['Bartolome Island','Snack'],
	['Bartolome Island','Tablespoon'],
	['Bartolome Island','Volcano'],
	['Battle of Midway','Sea Otter'],
	['Bearded Vulture','Recycling'],
	['Bearded Vulture','New York'],
	['Bearded Vulture','Recycling'],
	['Berlin','Barn Owl'],
	['Berlin Wall','Butchart Gardens'],
	['Berlin Wall','Derwent Reservoir'],
	['Berlin Wall','Fantasy Football'],
	['Berlin Wall','Greenland'],
	['Berlin Wall','New York'],
	['Berlin Wall','Paddleboarding'],
	['Berlin Wall','San Juan National Forest'],
	['Berlin Wall','Sudoku'],
	['Berlin Wall','Tornado'],
	['Berlin Wall','Wildebeest'],
	['Berlin Wall','World Elephant Day'],
	['Berlin Wall','Barn Owl'],
	['Berlin Wall','Butchart Gardens'],
	['Berlin Wall','Cheetah'],
	['Berlin Wall','Derwent Reservoir'],
	['Berlin Wall','Fantasy Football'],
	['Berlin Wall','Greenland'],
	['Berlin Wall','Munnar'],
	['Berlin Wall','New York'],
	['Berlin Wall','Paddleboarding'],
	['Berlin Wall','San Juan National Forest'],
	['Berlin Wall','Sudoku'],
	['Berlin Wall','Swimming'],
	['Berlin Wall','Tornado'],
	['Berlin Wall','Volcano'],
	['Berlin Wall','Wildebeest'],
	['Berlin Wall','World Elephant Day'],
	['Berlin Wall','Butchart Gardens'],
	['Bernese Alps','Barcelona'],
	['Bernese Alps','Broccoli'],
	['Bernese Alps','Caribbean'],
	['Bernese Alps','Chicago'],
	['Bernese Alps','Flamingo'],
	['Bernese Alps','Four Corners Monument'],
	['Bernese Alps','Goldendoodle'],
	['Bernese Alps','Grasslands National Park'],
	['Bernese Alps','Honolulu'],
	['Bernese Alps','Ice Cream'],
	['Bernese Alps','Ketogenic Diet'],
	['Bernese Alps','Los Angeles'],
	['Bernese Alps','Recycling'],
	['Bernese Alps','Snack'],
	['Bernese Alps','Sun Moon Lake'],
	['Bernese Alps','Barcelona'],
	['Bernese Alps','Broccoli'],
	['Bernese Alps','Caribbean'],
	['Bernese Alps','Chicago'],
	['Bernese Alps','Empire State Building'],
	['Bernese Alps','Flamingo'],
	['Bernese Alps','Four Corners Monument'],
	['Bernese Alps','Goldendoodle'],
	['Bernese Alps','Grasslands National Park'],
	['Bernese Alps','Honolulu'],
	['Bernese Alps','Ice Cream'],
	['Bernese Alps','Jupiter'],
	['Bernese Alps','Ketogenic Diet'],
	['Bernese Alps','Los Angeles'],
	['Bernese Alps','Recycling'],
	['Bernese Alps','Snack'],
	['Bernese Alps','Statue of Liberty'],
	['Bernese Alps','Sun Moon Lake'],
	['Bernese Alps','Texas'],
	['Bernese Alps','Broccoli'],
	['Bernese Alps','Jupiter'],
	['Bernese Alps','Statue of Liberty'],
	['Bhumibol Bridge','Butchart Gardens'],
	['Bhumibol Bridge','Nashville'],
	['Bhumibol Bridge','Tornado'],
	['Bhumibol Bridge','Volcano'],
	['Bhumibol Bridge','Amazon Rainforest'],
	['Bhumibol Bridge','Basketball'],
	['Bhumibol Bridge','Amazon Rainforest'],
	['Bhumibol Bridge','Basketball'],
	['Bhumibol Bridge','Butchart Gardens'],
	['Bhumibol Bridge','Memphis'],
	['Bhumibol Bridge','Nashville'],
	['Bhumibol Bridge','Recycling'],
	['Bhumibol Bridge','Tornado'],
	['Bhumibol Bridge','Volcano'],
	['Bhumibol Bridge','Woolly Mammoth'],
	['Bhumibol Bridge','Butchart Gardens'],
	['Bison','Fremont Peak'],
	['Bison','Jutland'],
	['Bison','Lord Howe Island'],
	['Bison','Jutland'],
	['Bison','Lord Howe Island'],
	['Bison ','Fremont Peak'],
	['Blueberry','Andalusia'],
	['Blueberry','Everglades'],
	['Blueberry','Greenland'],
	['Bojnice Castle','Barcelona'],
	['Bojnice Castle','Bearded Vulture'],
	['Bojnice Castle','Bhumibol Bridge'],
	['Bojnice Castle','Cabo San Lucas'],
	['Bojnice Castle','French Fries'],
	['Bojnice Castle','Hurricane Katrina'],
	['Bojnice Castle','Laguna Beach'],
	['Bojnice Castle','Lovebird'],
	['Bojnice Castle','Niagara Falls'],
	['Bojnice Castle','Pumpkin Pie'],
	['Bojnice Castle','Bald Eagle'],
	['Bojnice Castle','Barcelona'],
	['Bojnice Castle','Bearded Vulture'],
	['Bojnice Castle','Bhumibol Bridge'],
	['Bojnice Castle','Bald Eagle'],
	['Bojnice Castle','Barcelona'],
	['Bojnice Castle','Bearded Vulture'],
	['Bojnice Castle','Bhumibol Bridge'],
	['Bojnice Castle','Broccoli'],
	['Bojnice Castle','Cabo San Lucas'],
	['Bojnice Castle','Dance'],
	['Bojnice Castle','French Fries'],
	['Bojnice Castle','Hurricane Katrina'],
	['Bojnice Castle','Laguna Beach'],
	['Bojnice Castle','Lovebird'],
	['Bojnice Castle','Niagara Falls'],
	['Bojnice Castle','Pumpkin Pie'],
	['Bojnice Castle','Broccoli'],
	['Bora Bora','Bow Lake'],
	['Bora Bora','Cabo San Lucas'],
	['Bora Bora','Chess'],
	['Bora Bora','Death Valley National Park'],
	['Bora Bora','Drawing'],
	['Bora Bora','Empire State Building'],
	['Bora Bora','French Fries'],
	['Bora Bora','Junk Food'],
	['Bora Bora','Ketogenic Diet'],
	['Bora Bora','Laem Son National Park'],
	['Bora Bora','Lake of the Clouds'],
	['Bora Bora','Niagara Falls'],
	['Bora Bora','Pumpkin Pie'],
	['Bora Bora','Similan Islands'],
	['Bora Bora','Texas'],
	['Bora Bora','White Cliffs of Dover'],
	['Bora Bora','Amazon Rainforest'],
	['Bora Bora','Berlin Wall'],
	['Bora Bora','Amazon Rainforest'],
	['Bora Bora','Bow Lake'],
	['Bora Bora','Bruges'],
	['Bora Bora','Cabo San Lucas'],
	['Bora Bora','Chess'],
	['Bora Bora','Death Valley National Park'],
	['Bora Bora','Drawing'],
	['Bora Bora','Empire State Building'],
	['Bora Bora','French Fries'],
	['Bora Bora','Giraffe'],
	['Bora Bora','Hurricane Katrina'],
	['Bora Bora','Junk Food'],
	['Bora Bora','Ketogenic Diet'],
	['Bora Bora','Laem Son National Park'],
	['Bora Bora','Laguna Beach'],
	['Bora Bora','Lake of the Clouds'],
	['Bora Bora','Lighthouse'],
	['Bora Bora','Los Angeles'],
	['Bora Bora','Lovebird'],
	['Bora Bora','Monarch Butterfly'],
	['Bora Bora','Moon'],
	['Bora Bora','Niagara Falls'],
	['Bora Bora','Pumpkin Pie'],
	['Bora Bora','Shih Tzu'],
	['Bora Bora','Similan Islands'],
	['Bora Bora','Tahquamenon River'],
	['Bora Bora','Texas'],
	['Bora Bora','White Cliffs of Dover'],
	['Bora Bora','Bruges'],
	['Bora Bora','Giraffe'],
	['Bora Bora','Hurricane Katrina'],
	['Bora Bora','Los Angeles'],
	['Bow Lake','Broccoli'],
	['Bow Lake','Flamingo'],
	['Bow Lake','Goldendoodle'],
	['Bow Lake','Ice Cream'],
	['Bow Lake','Niagara Falls'],
	['Bow Lake','Tablespoon'],
	['Bow Lake','Zucchini'],
	['Bow Lake','Amazon Rainforest'],
	['Bow Lake','Amazon Rain Forest'],
	['Bow Lake','Broccoli'],
	['Bow Lake','Flamingo'],
	['Bow Lake','Goldendoodle'],
	['Bow Lake','Ice Cream'],
	['Bow Lake','Italy'],
	['Bow Lake','Memphis'],
	['Bow Lake','Niagara Falls'],
	['Bow Lake','Tablespoon'],
	['Bow Lake','Zucchini'],
	['Bow Lake','Broccoli'],
	['Broccoli','Cheetah'],
	['Broccoli','French Fries'],
	['Broccoli','Cheetah'],
	['Broccoli','French Fries'],
	['Broccoli','Everglades National Park'],
	['Bruges','Bearded Vulture'],
	['Bruges','Grasslands National Park'],
	['Bruges','Junk Food'],
	['Bruges','Niagara Falls'],
	['Bruges','Rabbit'],
	['Bruges','Tablespoon'],
	['Bruges','Bearded Vulture'],
	['Bruges','Grasslands National Park'],
	['Bruges','Ice Cream'],
	['Bruges','Junk Food'],
	['Bruges','Niagara Falls'],
	['Bruges','Rabbit'],
	['Bruges','Snack'],
	['Bruges','Tablespoon'],
	['Bulldog','Springbrook National Park'],
	['Bulldog','Bartolome Island'],
	['Bulldog','Springbrook National Park'],
	['Bulldog','Toco Toucan'],
	['Butchart Gardens','Amazon Rainforest'],
	['Butchart Gardens','Bearded Vulture'],
	['Butchart Gardens','Broccoli'],
	['Butchart Gardens','Flamingo'],
	['Butchart Gardens','Fremont Peak'],
	['Butchart Gardens','Grasslands National Park Hippopotamus'],
	['Butchart Gardens','Ice Cream'],
	['Butchart Gardens','Laguna Beach'],
	['Butchart Gardens','Lovebird'],
	['Butchart Gardens','Maldives'],
	['Butchart Gardens','Monarch Butterfly'],
	['Butchart Gardens','Niagara Falls'],
	['Butchart Gardens','Santa Catalina Island'],
	['Butchart Gardens','Shih Tzu'],
	['Butchart Gardens','Toco Toucan'],
	['Butchart Gardens','Amazon Rainforest'],
	['Butchart Gardens','Arches National Park'],
	['Butchart Gardens','Avocado'],
	['Butchart Gardens','Barcelona'],
	['Butchart Gardens','Bearded Vulture'],
	['Butchart Gardens','Broccoli'],
	['Butchart Gardens','Amazon Rainforest'],
	['Butchart Gardens','Arches National Park'],
	['Butchart Gardens','Avocado'],
	['Butchart Gardens','Barcelona'],
	['Butchart Gardens','Bearded Vulture'],
	['Butchart Gardens','Broccoli'],
	['Butchart Gardens','Flamingo'],
	['Butchart Gardens','Four Corners Monument'],
	['Butchart Gardens','Fremont Peak'],
	['Butchart Gardens','Grasslands National Park Hippopotamus'],
	['Butchart Gardens','Ice Cream'],
	['Butchart Gardens','Laguna Beach'],
	['Butchart Gardens','Lovebird'],
	['Butchart Gardens','Maldives'],
	['Butchart Gardens','Monarch Butterfly'],
	['Butchart Gardens','Niagara Falls'],
	['Butchart Gardens','Santa Catalina Island'],
	['Butchart Gardens','Shih Tzu'],
	['Butchart Gardens','Snack'],
	['Butchart Gardens','Statue of Liberty'],
	['Butchart Gardens','Toco Toucan'],
	['Cabo San Lucas','Argania'],
	['Cabo San Lucas','Bartolome Island'],
	['Cabo San Lucas','Bow Lake'],
	['Cabo San Lucas','Can-Can'],
	['Cabo San Lucas','Murlough Bay'],
	['Cabo San Lucas','Palace of Fine Arts'],
	['Cabo San Lucas','Salt Spring Island'],
	['Cabo San Lucas','Tornado'],
	['Cabo San Lucas','White Cliffs of Dover'],
	['Cabo San Lucas','Argania'],
	['Cabo San Lucas','Bartolome Island'],
	['Cabo San Lucas','Bow Lake'],
	['Calculator','Bald Eagle'],
	['Calculator','Barcelona'],
	['Calculator','Bearded Vulture'],
	['Calculator','Broccoli'],
	['Calculator','Caribbean'],
	['Calculator','French Fries'],
	['Calculator','Grizzly Bear'],
	['Calculator','Italy'],
	['Calculator','Jutland'],
	['Calculator','Ketogenic Diet'],
	['Calculator','Laguna Beach'],
	['Calculator','Lovebird'],
	['Calculator','Maldives'],
	['Calculator','Sea Otter'],
	['Calculator','Triple Falls'],
	['Calculator','White Cliffs of Dover'],
	['Calculator','Bald Eagle'],
	['Calculator','Barcelona'],
	['Calculator','Bearded Vulture'],
	['Calculator','Broccoli'],
	['Calculator','Gateway Arch'],
	['Cambridge Gulf','Italy'],
	['Cambridge Gulf','Shih Tzu'],
	['Cambridge Gulf','Italy'],
	['Cambridge Gulf','Shih Tzu'],
	['Can-Can','Bald Eagle'],
	['Can-Can','Cape Reinga'],
	['Can-Can','Flamingo'],
	['Can-Can','Grizzly Bear'],
	['Can-Can','Ketogenic Diet'],
	['Can-Can','Rabbit'],
	['Can-Can','Shih Tzu'],
	['Can-Can','Amazon Rainforest'],
	['Can-Can','Bald Eagle'],
	['Can-Can','Junk Food'],
	['Can-Can','Manatee'],
	['Can-Can','Junk Food'],
	['Can-Can','Manatee'],
	['Caribbean','Bartolome Island'],
	['Castle Point Lighthouse','Cheetah'],
	['Castle Point Lighthouse','Fantasy Football'],
	['Castle Point Lighthouse','Pumpkin Pie'],
	['Charles Bridge','Greenland'],
	['Cheetah','Amazon Rainforest'],
	['Cheetah','Avocado'],
	['Cheetah','Bald Eagle'],
	['Cheetah','Bhumibol Bridge'],
	['Cheetah','Bulldog'],
	['Cheetah','Chicago'],
	['Cheetah','Drawing'],
	['Cheetah','Empire State Building'],
	['Cheetah','Goldendoodle'],
	['Cheetah','Grasslands National Park'],
	['Cheetah','Lake Geneva'],
	['Cheetah','Los Angeles'],
	['Cheetah','Similan Islands'],
	['Cheetah','Tablespoon'],
	['Cheetah','Triple Falls'],
	['Cheetah','Palace of Westminster'],
	['Cheetah','Valley of Fire State Park'],
	['Cheetah','Amazon Rainforest'],
	['Cheetah','Avocado'],
	['Cheetah','Ayodhya'],
	['Cheetah','Bald Eagle'],
	['Cheetah','Bhumibol Bridge'],
	['Cheetah','Bulldog'],
	['Cheetah','Ayodhya'],
	['Chess','Recycling'],
	['Chess','Munnar'],
	['Chicago','Bartolome Island'],
	['Chicago','Bojnice Castle'],
	['Chicago','Lweisville Lake'],
	['Chicago','Lewisville Lake'],
	['Corfe Castle','Bhumibol Bridge'],
	['Corfe Castle','Bulldog'],
	['Corfe Castle','Caribbean'],
	['Corfe Castle','Dance'],
	['Corfe Castle','Drawing'],
	['Corfe Castle','French Fries'],
	['Corfe Castle','Ice Cream'],
	['Corfe Castle','Lighthouse'],
	['Corfe Castle','Los Angeles'],
	['Corfe Castle','Niagara Falls'],
	['Corfe Castle','Sailfish'],
	['Corfe Castle','Tahquamenon River'],
	['Corfe Castle','Texas'],
	['Corfe Castle','Bald Eagle'],
	['Corfe Castle','Bearded Vulture'],
	['Corfe Castle','Bhumibol Bridge'],
	['Corfe Castle','Bulldog'],
	['Corfe Castle','Lighthouse'],
	['Crossword','Avocado'],
	['Crossword','Bhumibol Bridge'],
	['Crossword','Bow Lake'],
	['Crossword','Castle Point Lighthouse'],
	['Crossword','Dance'],
	['Crossword','Giraffe'],
	['Crossword','Grizzly Bear'],
	['Crossword','Lighthouse'],
	['Crossword','Pennybacker Bridge'],
	['Crossword','Toco Toucan'],
	['Crossword','Avocado'],
	['Crossword','Basketball'],
	['Crossword','Bhumibol Bridge'],
	['Crossword','Bow Lake'],
	['Crossword','Haystack Rock'],
	['Dance','Lewisville Lake'],
	['Dance','Nashville'],
	['Dance','Tornado'],
	['Death Valley National Park','Bearded Vulture'],
	['Death Valley National Park','Lake Geneva'],
	['Death Valley National Park','Pumpkin Pie'],
	['Death Valley National Park','Recycling'],
	['Death Valley National Park','Texas'],
	['Death Valley National Park','Bearded Vulture'],
	['Derwent Reservoir','Bearded Vulture'],
	['Derwent Reservoir','Caribbean'],
	['Derwent Reservoir','Drawing'],
	['Derwent Reservoir','Empire State Building'],
	['Derwent Reservoir','Haystack Rock'],
	['Derwent Reservoir','Laguna Beach'],
	['Derwent Reservoir','Lake Geneva'],
	['Derwent Reservoir','Lighthouse'],
	['Derwent Reservoir','Niagara Falls'],
	['Derwent Reservoir','Palace of Westminster'],
	['Derwent Reservoir','Sun Moon Lake'],
	['Derwent Reservoir','Bearded Vulture'],
	['Dow Jones','Chess'],
	['Drawing','Argania'],
	['Drawing','Bernese Alps'],
	['Drawing','Bow Lake'],
	['Drawing','Fantasy Football'],
	['Drawing','Hawaii'],
	['Drawing','Hippopotamus'],
	['Drawing','Isalo National Park'],
	['Drawing','Recycling'],
	['Drawing','Salt Spring Island'],
	['Drawing','Volcano'],
	['Drawing','White Cliffs of Dover'],
	['Drawing','Argania'],
	['Drawing','Bartolome Island'],
	['Drawing','Bernese Alps'],
	['Drawing','Bojnice Castle'],
	['Drawing','Bow Lake'],
	['Durdevica Tara Bridge','Amazon Rainforest'],
	['Durdevica Tara Bridge','Dance'],
	['Durdevica Tara Bridge','Drawing'],
	['Durdevica Tara Bridge','Moon'],
	['Durdevica Tara Bridge','Amazon Rainforest'],
	['Everglades National Park','Barcelona'],
	['Everglades National Park','Bhumibol Bridge'],
	['Everglades National Park','Dance'],
	['Everglades National Park','Flamingo'],
	['Everglades National Park','Junk Food'],
	['Everglades National Park','Laem Son National Park'],
	['Everglades National Park','Los Angeles'],
	['Everglades National Park','Murlough Bay'],
	['Everglades National Park','Sailfish'],
	['Everglades National Park','Shih Tzu'],
	['Everglades National Park','Snack'],
	['Everglades National Park','Triple Falls'],
	['Everglades National Park','Zucchini'],
	['Everglades National Park','Barcelona'],
	['Everglades National Park','Bhumibol Bridge'],
	['Fantasy Football','Bulldog'],
	['Fantasy Football','Empire State Building'],
	['Fantasy Football','Grasslands National Park'],
	['Fantasy Football','Grizzly Bear'],
	['Fantasy Football','Haystack Rock'],
	['Fantasy Football','Pumpkin Pie'],
	['Fantasy Football','Tablespoon'],
	['Fantasy Football','Bulldog'],
	['Fort Lauderdale','Wajima'],
	['Four Corners Monument','International Space Station'],
	['Four Corners Monument','New York'],
	['Four Corners Monument','Bulldog'],
	['Freemont Peak','Bearded Vulture'],
	['Fremont Peak','Bulldog'],
	['Fremont Peak','Flamingo'],
	['Fremont Peak','Giraffe'],
	['Fremont Peak','Los Angeles'],
	['Fremont Peak','Texas'],
	['Fremont Peak','Volcano'],
	['Fremont Peak','Bulldog'],
	['Fremont Peak','Beared Vulture'],
	['Garden of the Gods','Barcelona'],
	['Garden of the Gods','Basketball'],
	['Garden of the Gods','Bearded Vulture'],
	['Garden of the Gods','Cabo San Lucas'],
	['Garden of the Gods','Cape Reinga'],
	['Garden of the Gods','Chess'],
	['Garden of the Gods','Fremont Peak'],
	['Garden of the Gods','French Fries'],
	['Garden of the Gods','Grizzly Bear'],
	['Garden of the Gods','Haystack Rock'],
	['Garden of the Gods','Hippopotamus'],
	['Garden of the Gods','Hurricane Katrina'],
	['Garden of the Gods','Ketogenic Diet'],
	['Garden of the Gods','Lovebird'],
	['Garden of the Gods','Murlough Bay'],
	['Garden of the Gods','Pumpkin Pie'],
	['Garden of the Gods','Rabbit'],
	['Garden of the Gods','Sailfish'],
	['Garden of the Gods','Tablespoon'],
	['Garden of the Gods','Barcelona'],
	['Garden of the Gods','Basketball'],
	['Garden of the Gods','Bearded Vulture'],
	['Garden of the Gods','Bhumibol Bridge'],
	['Garden of the Gods','Bearded Vulture'],
	['Garden of the Gods','Rihanna'],
	['Giraffe','Barn Owl'],
	['Goldendoodle','Hurricane Katrina'],
	['Goldendoodle','Bartolome Island'],
	['Grasslands National Park','Tornado'],
	['Great Barrier Reef','Andalusia'],
	['Great Barrier Reef','Bald Eagle'],
	['Great Barrier Reef','Bernese Alps'],
	['Great Barrier Reef','Broccoli'],
	['Great Barrier Reef','Caribbean'],
	['Great Barrier Reef','Dance'],
	['Great Barrier Reef','Drawing'],
	['Great Barrier Reef','Flamingo'],
	['Great Barrier Reef','Giraffe'],
	['Great Barrier Reef','Grasslands National Park'],
	['Great Barrier Reef','Italy'],
	['Great Barrier Reef','Lighthouse'],
	['Great Barrier Reef','Lovebird'],
	['Great Barrier Reef','Sea Otter'],
	['Great Barrier Reef','Shih Tzu'],
	['Great Barrier Reef','Andalusia'],
	['Great Barrier Reef','Bald Eagle'],
	['Great Barrier Reef','Bernese Alps'],
	['Great Barrier Reef','Broccoli'],
	['Great Barrier Reef','Eiffel Tower'],
	['Greenland','Avocado'],
	['Greenland','Bhumibol Bridge'],
	['Greenland','French Fries'],
	['Greenland','Giraffe'],
	['Greenland','Ice Cream'],
	['Greenland','Laem Son National Park'],
	['Greenland','Laguna Beach'],
	['Greenland','Lake of the Clouds'],
	['Greenland','Lake Tekapo'],
	['Greenland','Lighthouse'],
	['Greenland','Monarch Butterfly'],
	['Greenland','Moon Hill'],
	['Greenland','Niagara Falls'],
	['Greenland','Pennybacker Bridge'],
	['Greenland','Similan Islands'],
	['Greenland','Snack'],
	['Greenland','Tahquamenon River'],
	['Greenland','Texas'],
	['Greenland','Toco Toucan'],
	['Greenland','Avocado'],
	['Greenland','Bhumibol Bridge'],
	['Grizzly Bear','Andalusia'],
	['Guanaco','Avocado'],
	['Guanaco','Cabo San Lucas'],
	['Guanaco','Chess'],
	['Guanaco','Dance'],
	['Guanaco','Four Corners Monument'],
	['Guanaco','Honolulu'],
	['Guanaco','Snack'],
	['Guanaco','Texas'],
	['Guanaco','Triple Falls'],
	['Guanaco','Avocado'],
	['Guanaco','Kelly Clarkson'],
	['Gunaco','Bulldog'],
	['Hawaii','Lake Michigan'],
	['Hawaii','Ozark National Scenic Riverways'],
	['Hawaii','Bearded Vulture'],
	['Hawaii','Avocado'],
	['Hawaii','Bearded Vulture'],
	['Haystack Rock','Bulldog'],
	['Haystack Rock','New York'],
	['Haystack Rock','Tornado'],
	['Haystack Rock','Volcano'],
	['Haystack Rock','Broccoli'],
	['Haystack Rock','Bulldog'],
	['Hippopotamus','Barcelona'],
	['Hippopotamus','Broccoli'],
	['Hippopotamus','Bulldog'],
	['Hippopotamus','Empire State Building'],
	['Hippopotamus','Four Corners Monument'],
	['Hippopotamus','Laguna Beach'],
	['Hippopotamus','Los Angeles'],
	['Hippopotamus','Manatee'],
	['Hippopotamus','Barcelona'],
	['Hippopotamus','Broccoli'],
	['Hippopotamus','Bulldog'],
	['Honolulu','International Space Station'],
	['Ice Cream','Bartolome Island'],
	['Ice Cream','Recycling'],
	['Ice Cream','Tennessee'],
	['Ice Cream','Bartolome Island'],
	['International Space Station','Barcelona'],
	['Isalo National Park','Bald Eagle'],
	['Isalo National Park','Barcelona'],
	['Isalo National Park','Bulldog'],
	['Isalo National Park','Chess'],
	['Isalo National Park','Eiffel Tower'],
	['Isalo National Park','Four Corners Monument'],
	['Isalo National Park','Goldendoodle'],
	['Isalo National Park','Grizzly Bear'],
	['Isalo National Park','Honolulu'],
	['Isalo National Park','Pumpkin Pie'],
	['Isalo National Park','Snack'],
	['Isalo National Park','Sun Moon Lake'],
	['Isalo National Park','Triple Falls'],
	['Isalo National Park','Bald Eagle'],
	['Isalo National Park','Barcelona'],
	['Isalo National Park','Bearded Vulture'],
	['Isalo National Park','Blueberry'],
	['Isalo National Park','Bulldog'],
	['Isalo National Park','Blueberry'],
	['Italy','Andalusia'],
	['Italy','Arches National Park'],
	['Italy','Bow Lake'],
	['Italy','Bruges'],
	['Italy','Can-Can'],
	['Italy','Lewisville Lake'],
	['Italy','Munnar'],
	['Italy','New York'],
	['Italy','Olkhon Island'],
	['Italy','Salt Spring Island'],
	['Italy','Volcano'],
	['Italy','White Cliffs of Dover'],
	['Italy','Woolly Mammoth'],
	['Italy','Andalusia'],
	['Italy','Arches National Park'],
	['Italy','Bruges'],
	['Junk Food','Hawaii'],
	['Jutland','Amazon Rainforest Bearded Vulture'],
	['Jutland','Bulldog'],
	['Jutland','Cape Reinga'],
	['Jutland','Caribbean'],
	['Jutland','Giraffe'],
	['Jutland','Grasslands National Park'],
	['Jutland','Junk Food'],
	['Jutland','Ketogenic Diet'],
	['Jutland','Los Angeles'],
	['Jutland','Niagara Falls'],
	['Jutland','Pumpkin Pie'],
	['Jutland','Snack'],
	['Jutland','Sun Moon Lake'],
	['Jutland','Volcano'],
	['Jutland','Amazon Rainforest'],
	['Jutland','Barcelona'],
	['Jutland','Bearded Vulture'],
	['Jutland','Broccoli'],
	['Jutland','Bulldog'],
	['Jutland','Statue of Liberty'],
	['Kelly Clarkson','Arches National Park'],
	['Kelly Clarkson','Bernese Alps'],
	['Kelly Clarkson','Spanish Steps'],
	['Ketogenic Diet','Recycling'],
	['Krakatao','Bhumibol Bridge'],
	['Krakatoa','Avocado'],
	['Krakatoa','Cabo San Lucas'],
	['Krakatoa','Cape Reinga'],
	['Krakatoa','Caribbean'],
	['Krakatoa','Chess'],
	['Krakatoa','Empire State Building'],
	['Krakatoa','Grizzly Bear'],
	['Krakatoa','Isalo National Park'],
	['Krakatoa','Moon'],
	['Krakatoa','Murlough Bay'],
	['Krakatoa','Pumpkin Pie'],
	['Krakatoa','Zucchini'],
	['Krakatoa','Broccoli'],
	['Kylemore Abbey','Castle Point Lighthouse'],
	['Laem Son National Park','Hawaii'],
	['Laem Son National Park','Memphis'],
	['Laem Son National Park','Nashville'],
	['Laem Son National Park','Tennessee'],
	['Laem Son National Park','Volcano'],
	['Laem Son National Park','Broccoli'],
	['Laem Son National Park','Memphis'],
	['Lake Geneva','Niagara Falls'],
	['Lake Geneva','Recycling'],
	['Lake Geneva','Tornado'],
	['Lake of the Clouds','Bulldog'],
	['Lake of the Clouds','Four Corners Monument'],
	['Lake of the Clouds','Hawaii'],
	['Lake of the Clouds','Los Angeles'],
	['Lake of the Clouds','Nashville'],
	['Lake of the Clouds','Volcano'],
	['Lake of the Clouds','Zucchini'],
	['Lake of the Clouds','Bulldog'],
	['Lake Tekapo','Barn Owl'],
	['Lake Tekapo','Derwent Reservoir'],
	['Lake Tekapo','Drawing'],
	['Lake Tekapo','Everglades National Park'],
	['Lake Tekapo','Hawaii'],
	['Lake Tekapo','International Space Station'],
	['Lake Tekapo','Memphis'],
	['Lake Tekapo','Tornado'],
	['Lake Tekapo','Volcano'],
	['Lake Tekapo','Barn Owl'],
	['Lake Tekapo','Tablespoon'],
	['Lewisville Lake','Bald Eagle'],
	['Lewisville Lake','Bulldog'],
	['Lewisville Lake','Cabo San Lucas'],
	['Lewisville Lake','Giraffe'],
	['Lewisville Lake','Grasslands'],
	['Lewisville Lake','Honolulu'],
	['Lewisville Lake','Junk Food'],
	['Lewisville Lake','Lovebird'],
	['Lewisville Lake','Manatee'],
	['Lewisville Lake','Moon'],
	['Lewisville Lake','Niagara Falls'],
	['Lewisville Lake','Pumpkin Pie'],
	['Lewisville Lake','Snack'],
	['Lewisville Lake','Amazon Rainforest'],
	['Lewisville Lake','Bald Eagle'],
	['Lewisville Lake','Bearded Vulture'],
	['Lewisville Lake','Bulldog'],
	['Lighthouse','Bulldog'],
	['Lighthouse','Memphis'],
	['Lighthouse','Nashville'],
	['Lighthouse','Bulldog'],
	['Lord Howe Island','Barcelona'],
	['Lord Howe Island','Chicago'],
	['Lord Howe Island','Giraffe'],
	['Lord Howe Island','Ice Cream'],
	['Lord Howe Island','Ketogenic Diet'],
	['Lord Howe Island','Lighthouse'],
	['Lord Howe Island','Los Angeles'],
	['Lord Howe Island','Manatee'],
	['Lord Howe Island','Rabbit'],
	['Lord Howe Island','Tablespoon'],
	['Lord Howe Island','Texas'],
	['Lord Howe Island','Barcelona'],
	['Lord Howe Island','Bhumibol Bridge'],
	['Lord Howe Island','Bulldog'],
	['Lord Howe Island','Laguna Beach'],
	['Los Angeles','Lingmoor Fell'],
	['Lose Angeles','Lingmoor Fell'],
	['Lovebird','Nashville'],
	['Lung','Argania'],
	['Macarena','Bearded Vulture'],
	['Macarena','Castle Point Lighthouse'],
	['Macarena','Chicago'],
	['Macarena','Hurricane Katrina'],
	['Macarena','Junk Food'],
	['Macarena','Laem Son National Park'],
	['Macarena','Lighthouse'],
	['Macarena','Murlough Bay'],
	['Macarena','Pumpkin Pie'],
	['Macarena','Santa Catalina Island'],
	['Macarena','Bearded Vulture'],
	['Madikwe Game Reserve','Burger King'],
	['Maldives','Bald Eagle'],
	['Maldives','Chess'],
	['Maldives','Chicago'],
	['Maldives','Drawing'],
	['Maldives','Giraffe'],
	['Maldives','Goldendoodle'],
	['Maldives','Grizzly Bear Junk Food'],
	['Maldives','Ketogenic Diet'],
	['Maldives','Sailfish'],
	['Maldives','Shih Tzu'],
	['Maldives','Sun Moon Lake'],
	['Maldives','Tablespoon'],
	['Maldives','Texas'],
	['Maldives','Triple Falls'],
	['Maldives','Bald Eagle'],
	['Maldives','Barcelona'],
	['Maldives','Zucchini'],
	['Manatee','Bruges'],
	['Manatee','Can-Can'],
	['Manatee','Fremont Peak'],
	['Manatee','Jutland'],
	['Manatee','Memphis'],
	['Manatee','Munnar'],
	['Manatee','Palace of Fine Arts'],
	['Manatee','Similan Islands'],
	['Manatee','Toco Toucan'],
	['Manatee','Tornado'],
	['Manatee','Bruges'],
	['Martha\'s Vineyard','Bearded Vulture'],
	['Martha\'s Vineyard','Chicago'],
	['Martha\'s Vineyard','Four Corners Monument'],
	['Martha\'s Vineyard','Honolulu'],
	['Martha\'s Vineyard','Ketogenic Diet'],
	['Martha\'s Vineyard','Laguna Beach'],
	['Martha\'s Vineyard','Lovebird'],
	['Martha\'s Vineyard','Sailfish'],
	['Martha\'s Vineyard','Shih Tzu'],
	['Martha\'s Vineyard','Tablespoon'],
	['Martha\'s Vineyard','Zucchini'],
	['Martha\'s Vineyard','Bearded Vulture'],
	['Memphis','Empire State Building'],
	['Memphis','Shih Tzu'],
	['Memphis','Snack'],
	['Monarch Butterfly','Hawaii'],
	['Monarch Butterfly','Lewisville Lake'],
	['Monarch Butterfly','Lord Howe Island'],
	['Monarch Butterfly','Mount Everest'],
	['Monarch Butterfly','Munnar'],
	['Monarch Butterfly','Salt Spring Island'],
	['Monarch Butterfly','Saskatchewan'],
	['Monarch Butterfly','Tornado'],
	['Moon','Broccoli'],
	['Moon','Bulldog'],
	['Moon','New York'],
	['Moon','Tornado'],
	['Moon','Volcano'],
	['Moon','Broccoli'],
	['Moon','Bulldog'],
	['Moon','Saskatchewan'],
	['Moon Hill','Grasslands National Park'],
	['Moon Hill','Junk Food'],
	['Moon Hill','Los Angeles'],
	['Moon Hill','Sun Moon Lake'],
	['Moon Hill','Texas'],
	['Moon Hill','World Elephant Day'],
	['Moon Hill','Goldendoodle'],
	['Moon Hill','Swimming'],
	['Mount Everest','Barcelona'],
	['Mount Everest','Broccoli'],
	['Mount Everest','Chicago'],
	['Mount Everest','French Fries'],
	['Mount Everest','Giraffe'],
	['Mount Everest','Hurricane Katrina'],
	['Mount Everest','Laguna Beach'],
	['Mount Everest','Lovebird'],
	['Mount Everest','Manatee'],
	['Mount Everest','Moon'],
	['Mount Everest','Sailfish'],
	['Mount Everest','Sun Moon Lake'],
	['Mount Everest','Zucchini'],
	['Mount Everest','Barcelona'],
	['Mount Everest','Bearded Vulture'],
	['Mount Everest','Bhumibol Bridge'],
	['Mount Everest','Broccoli'],
	['Munnar','Amazon Rainforest'],
	['Munnar','Giraffe'],
	['Munnar','Goldendoodle'],
	['Munnar','Grasslands National Park'],
	['Munnar','Triple Falls'],
	['Munnar','Zucchini'],
	['Munnar','Amazon Rainforest'],
	['Munnar','Candy'],
	['Murlough Bay','Bald Eagle'],
	['Murlough Bay','Bearded Vulture'],
	['Murlough Bay','Caribbean'],
	['Murlough Bay','Hawaii'],
	['Murlough Bay','Recycling'],
	['Murlough Bay','Amazon Rainforest'],
	['Murlough Bay','Bald Eagle'],
	['Murlough Bay','Bearded Vulture'],
	['Murlough Bay','Eiffel Tower'],
	['Murlough Bay','Siberian Tiger'],
	['Muunar','Candy'],
	['Naples','New York'],
	['Nashville','Amazon Rainforest'],
	['Nashville','Caribbean'],
	['Nashville','Flamingo'],
	['Nashville','Tokyo'],
	['Nashville','Amazon Rainforest'],
	['Nashville','Berlin Wall'],
	['Nashville','White Cliffs of Dover'],
	['New York','Grizzly Bear'],
	['New York','Junk Food'],
	['New York','Burger King'],
	['Niagara Falls','Nashville'],
	['Niagara Falls','Recycling'],
	['Ocho Rios','Amazon Rainforest'],
	['Ocho Rios','Texas'],
	['Olkhon Island','Bald Eagle'],
	['Olkhon Island','Bearded Vulture'],
	['Olkhon Island','Broccoli'],
	['Olkhon Island','Cape Reinga'],
	['Olkhon Island','Four Corners Monument'],
	['Olkhon Island','Giraffe'],
	['Olkhon Island','Grasslands National Park'],
	['Olkhon Island','Ice Cream'],
	['Olkhon Island','Junk Food'],
	['Olkhon Island','Ketogenic Diet'],
	['Olkhon Island','Nashville'],
	['Olkhon Island','Snack'],
	['Olkhon Island','Tablespoon'],
	['Olkhon Island','Bald Eagle'],
	['Olkhon Island','Bearded Vulture'],
	['Olkhon Island','Broccoli'],
	['Olkhon Island','Caribbean'],
	['Ozark National Scenic Riverways','Cape Reinga'],
	['Ozark National Scenic Riverways','Junk Food'],
	['Ozark National Scenic Riverways','Snack'],
	['Paddleboarding','Bulldog'],
	['Paddleboarding','Chicago'],
	['Paddleboarding','Empire State Building'],
	['Paddleboarding','Grizzly Bear'],
	['Paddleboarding','Haystack Rock'],
	['Paddleboarding','Hurricane Katrina'],
	['Paddleboarding','Ketogenic Diet'],
	['Paddleboarding','Laem Son National Park'],
	['Paddleboarding','Los Angeles'],
	['Paddleboarding','Manatee'],
	['Paddleboarding','Moon'],
	['Paddleboarding','Niagara Falls'],
	['Paddleboarding','Rabbit'],
	['Paddleboarding','Similan Islands'],
	['Paddleboarding','White Cliffs of Dover'],
	['Paddleboarding','Amazon Rainforest'],
	['Paddleboarding','Bearded Vulture'],
	['Paddleboarding','Bulldog'],
	['Paddleboarding','Lake Michigan'],
	['Palace of Fine Arts','Cape Reinga'],
	['Palace of Fine Arts','Caribbean'],
	['Palace of Fine Arts','Giraffe'],
	['Palace of Fine Arts','Goldendoodle'],
	['Palace of Fine Arts','Sailfish'],
	['Palace of Fine Arts','Texas'],
	['Palace of Fine Arts','Tornado'],
	['Palace of Fine Arts','Bearded Vulture'],
	['Palace of Westminster','Hawaii'],
	['Palace of Westminster','Tablespoon'],
	['Palace of Westminster','Amazon Rainforest'],
	['Palace of Westminster','Wildebeest'],
	['Patrick Mahomes','New York'],
	['Pennybacker Bridge','Recycling'],
	['Pennybacker Bridge','Volcano'],
	['Pennybacker Bridge','Bald Eagle'],
	['Pennybacker Bridge','Four Corners Monument'],
	['Pumpkim Pie','Andalusia'],
	['Pumpkim Pie','Bartolome Island'],
	['Pumpkin Pie','Andalusia'],
	['Pumpkin Pie','Bartolome Island'],
	['Pumpkin Pie','Munnar'],
	['Pumpkin Pie','New York'],
	['Pumpkin Pie','Olkhon Island'],
	['Pumpkin Pie','Salt Spring Island'],
	['Pumpkin Pie','Argania'],
	['Puyallup','Ribadeo'],
	['Rabbit','Tornado'],
	['Rapa Valley','Broccoli'],
	['Rapa Valley','Bulldog'],
	['Rapa Valley','Caribbean'],
	['Rapa Valley','Flamingo'],
	['Rapa Valley','Giraffe'],
	['Rapa Valley','Goldendoodle'],
	['Rapa Valley','Honolulu'],
	['Rapa Valley','Junk Food'],
	['Rapa Valley','Los Angeles'],
	['Rapa Valley','Manatee'],
	['Rapa Valley','Rabbit'],
	['Rapa Valley','Sun Moon Lake'],
	['Rapa Valley','Tarutao National Marine Park'],
	['Rapa Valley','Broccoli'],
	['Rapa Valley','Bulldog'],
	['Rapa Valley','Rabbit'],
	['Recycling','Bulldog'],
	['Recycling','Caribbean'],
	['Recycling','Amazon Rainforest'],
	['Recycling','Bulldog'],
	['Recycling','Sailfish'],
	['Rihanna','Lingmoor Fell'],
	['Sailfish','Hawaii'],
	['Sailfish','Nashville'],
	['Sailfish','Argania'],
	['Salt Spring Island','Bulldog'],
	['Salt Spring Island','Goldendoodle'],
	['Salt Spring Island','Haystack Rock'],
	['Salt Spring Island','Sailfish'],
	['Salt Spring Island','Shih Tzu'],
	['Salt Spring Island','Blueberry'],
	['Salt Spring Island','Bulldog'],
	['Salt Spring Island','Grasslands National Park'],
	['Salt Spring Island','Sailfish'],
	['Salt Spring Island','Grasslands National Park'],
	['Salt Spring Island','Sailfish'],
	['San Juan National Forest','Amazon Rainforest'],
	['San Juan National Forest','Bow Lake'],
	['San Juan National Forest','Bhumibol Bridge'],
	['San Juan National Forest','Chess'],
	['San Juan National Forest','Empire State Building'],
	['San Juan National Forest','Haystack Rock'],
	['San Juan National Forest','Hurricane Katrina'],
	['San Juan National Forest','Ice Cream'],
	['San Juan National Forest','Moon'],
	['San Juan National Forest','Palace of Westminster'],
	['San Juan National Forest','Pumpkin Pie'],
	['San Juan National Forest','Amazon Rainforest'],
	['San Juan National Forest','Lake of the Clouds'],
	['San Juan National Park','Bhumibol Bridge'],
	['San Juan National Park','Bow Lake'],
	['Santa Catalina Island','Tornado'],
	['Santa Catalina Island','Volcano'],
	['Santa Catalina Island','Paddleboarding'],
	['Santa Monica Pier','Caribbean'],
	['Santa Monica Pier','Saskatchewan'],
	['Sardinia','Bernese Alps'],
	['Sardinia','Bhumibol Bridge'],
	['Sardinia','Broccoli'],
	['Sardinia','Bulldog'],
	['Sardinia','Chess'],
	['Sardinia','Chicago'],
	['Sardinia','Goldendoodle'],
	['Sardinia','Grasslands National Park'],
	['Sardinia','Grizzly Bear'],
	['Sardinia','Haystack Rock'],
	['Sardinia','Hurricane Katrina'],
	['Sardinia','Ketogenic Diet'],
	['Sardinia','Lighthouse'],
	['Sardinia','Los Angeles'],
	['Sardinia','Lovebird'],
	['Sardinia','Manatee'],
	['Sardinia','Moon'],
	['Sardinia','Moon Hill'],
	['Sardinia','Palace of Westminster'],
	['Sardinia','Santa Catalina Island'],
	['Sardinia','Sea Otter'],
	['Sardinia','Sun Moon Lake'],
	['Sardinia','Tarutao National Marine Park'],
	['Sardinia','Zucchini'],
	['Sardinia','Bernese Alps'],
	['Sardinia','Bhumibol Bridge'],
	['Sardinia','Broccoli'],
	['Sardinia','Bulldog'],
	['Sardinia','Lovebird'],
	['Sardinia','Sailfish'],
	['Sardinia','Lovebird'],
	['Sardinia','Sailfish'],
	['Saskatchewan','Barcelona'],
	['Saskatchewan','Bhumibol Bridge'],
	['Saskatchewan','Cape Reinga'],
	['Saskatchewan','Chicago'],
	['Saskatchewan','Goldendoodle'],
	['Saskatchewan','Junk Food'],
	['Saskatchewan','Laem Son National Park'],
	['Saskatchewan','Lovebird'],
	['Saskatchewan','Palace of Westminster'],
	['Saskatchewan','Valley of Fire State Park'],
	['Saskatchewan','Barcelona'],
	['Saskatchewan','Bearded Vulture'],
	['Saskatchewan','Bhumibol Bridge'],
	['Sea Otter','Bulldog'],
	['Sea Otter','Fantasy Football'],
	['Sea Otter','Garden of the Gods'],
	['Sea Otter','Paddleboarding'],
	['Sea Otter','Tablespoon'],
	['Sea Otter','Recycling'],
	['Sea Otter','Volcano'],
	['Sea Otter','Bulldog'],
	['Seven Sisters Sussex','Amazon Rainforest'],
	['Seven Sisters, Sussex','Bald Eagle'],
	['Seven Sisters, Sussex','Bulldog'],
	['Seven Sisters, Sussex','Chess'],
	['Seven Sisters, Sussex','Chicago'],
	['Seven Sisters, Sussex','Flamingo'],
	['Seven Sisters, Sussex','Four Corners Monument'],
	['Seven Sisters, Sussex','Giraffe'],
	['Seven Sisters, Sussex','Goldendoodle'],
	['Seven Sisters, Sussex','Grasslands National Park'],
	['Seven Sisters, Sussex','Honolulu'],
	['Seven Sisters, Sussex','Los Angeles'],
	['Seven Sisters, Sussex','Pumpkin Pie'],
	['Seven Sisters, Sussex','Rabbit'],
	['Seven Sisters, Sussex','Sailfish'],
	['Seven Sisters, Sussex','Tablespoon'],
	['Seven Sisters, Sussex','Texas'],
	['Seven Sisters, Sussex','Zucchini'],
	['Seven Sisters, Sussex','Bald Eagle'],
	['Seven Sisters, Sussex','Broccoli'],
	['Seven Sisters, Sussex','Bulldog'],
	['Seven Sisters, Sussex','Jupiter'],
	['Siberian Tiger','Fantasy Football'],
	['Siberian Tiger','Murlough Bay'],
	['Similan Islands','Bulldog'],
	['Similan Islands','Memphis'],
	['Similan Islands','Bulldog'],
	['Snack','International Space Station'],
	['Snack','Fantasy Football'],
	['Spanish Steps','Barcelona'],
	['Spanish Steps','Cape Reinga'],
	['Spanish Steps','Caribbean'],
	['Spanish Steps','Four Corners Monument'],
	['Spanish Steps','French Fries'],
	['Spanish Steps','Giraffe'],
	['Spanish Steps','Hurricane Katrina'],
	['Spanish Steps','Italy'],
	['Spanish Steps','Junk Food'],
	['Spanish Steps','Ketogenic Diet'],
	['Spanish Steps','Monarch Butterfly'],
	['Spanish Steps','Murlough Bay'],
	['Spanish Steps','Niagara Falls'],
	['Spanish Steps','Sailfish'],
	['Spanish Steps','Sea Otter'],
	['Spanish Steps','Snack'],
	['Spanish Steps','Sun Moon Lake'],
	['Spanish Steps','Toco Toucan'],
	['Spanish Steps','Barcelona'],
	['Springbrook National Park','Chess'],
	['Springbrook National Park','Hurricane Katrina'],
	['Springbrook National Park','Laguna Beach'],
	['Springbrook National Park','Pumpkin Pie'],
	['Sudoku','Bald Eagle'],
	['Sudoku','Barcelona'],
	['Sudoku','Castle Point Lighthouse'],
	['Sudoku','Empire State Building'],
	['Sudoku','Ice Cream'],
	['Sudoku','Italy'],
	['Sudoku','Junk Food'],
	['Sudoku','Lake Tekapo'],
	['Sudoku','Lighthouse'],
	['Sudoku','Los Angeles'],
	['Sudoku','Palace of Westminster'],
	['Sudoku','Santa Catalina Island'],
	['Sudoku','Shih Tzu'],
	['Sudoku','Tahquamenon River'],
	['Sudoku','Tarutao National Marine Park'],
	['Sudoku','Texas'],
	['Sudoku','Triple Falls'],
	['Sudoku','Avocado'],
	['Sudoku','Ayodhya'],
	['Sudoku','Bald Eagle'],
	['Sudoku','Barcelona'],
	['Sudoku','Bartolome Island'],
	['Sudoku','Bearded Vulture'],
	['Sudoku','Avocado'],
	['Sudoku','Whirlpool Galaxy'],
	['Sun Moon Lake','Andalusia'],
	['Sun Moon Lake','Hawaii'],
	['Sun Moon Lake','Martha\'s Vineyard'],
	['Sun Moon Lake','Tornado'],
	['Sun Moon Lake','Andalusia'],
	['Sun Moon Lake','Gateway Arch'],
	['Swimming','Barcelona'],
	['Swimming','Bartolome Island'],
	['Swimming','Bearded Vulture'],
	['Swimming','Bow Lake'],
	['Swimming','Dance'],
	['Swimming','Death Valley National Park'],
	['Swimming','Grasslands National Park'],
	['Swimming','Moon'],
	['Swimming','Murlough Bay'],
	['Swimming','Niagara Falls'],
	['Swimming','Shih Tzu'],
	['Swimming','Tablespoon'],
	['Swimming','Toco Toucan'],
	['Swimming','Barcelona'],
	['Swimming','Bartolome Island'],
	['Swimming','Bearded Vulture'],
	['Swimming','Bow Lake'],
	['Swimming','Lovebird'],
	['Tahquamenon River','Everglades National Park'],
	['Tahquamenon River','Nashville'],
	['Tahquamenon River','Rabbit'],
	['Tahquamenon River','Volcano'],
	['Tahquamenon River','World Elephant Day'],
	['Tarutao National Marine Park','International Space Station'],
	['Tarutao National Marine Park','Volcano'],
	['Tennessee','Bartolome Island'],
	['Tennessee','Bernese Alps'],
	['Tennessee','Cape Reinga'],
	['Tennessee','Castle Point Lighthouse'],
	['Tennessee','Drawing'],
	['Tennessee','Fremont Peak'],
	['Tennessee','Goldendoodle'],
	['Tennessee','Junk Food'],
	['Tennessee','Lake Tekapo'],
	['Tennessee','Lighthouse'],
	['Tennessee','Monarch Butterfly'],
	['Tennessee','Moon Hill'],
	['Tennessee','Niagara Falls'],
	['Tennessee','Pennybacker Bridge'],
	['Tennessee','Pumpkin Pie'],
	['Tennessee','Shih Tzu'],
	['Tennessee','Tahquamenon River'],
	['Tennessee','Valley of Fire State Park'],
	['Tennessee','Bartolome Island'],
	['Tennessee','Bernese Alps'],
	['Tennessee','Goldendoodle'],
	['Texas','Tornado'],
	['Texas','Volcano'],
	['Thanksgiving','Acadia National Park'],
	['Thanksgiving','Andalusia'],
	['Thanksgiving','Arches National Park'],
	['Thanksgiving','Can-Can'],
	['Thanksgiving','Corfe Castle'],
	['Thanksgiving','Fremont Peak'],
	['Thanksgiving','Greenland'],
	['Thanksgiving','Guanaco'],
	['Thanksgiving','Lewisville Lake'],
	['Thanksgiving','Memphis'],
	['Thanksgiving','New York'],
	['Thanksgiving','Palace of Fine Arts'],
	['Thanksgiving','Rapa Valley'],
	['Thanksgiving','Recycling'],
	['Thanksgiving','Sardinia'],
	['Thanksgiving','Spanish Steps'],
	['Thanksgiving','Wildebeest'],
	['Thanksgiving','Andalusia'],
	['Thanksgiving','Arches National Park'],
	['Theodore Roosevelt National Park','Avocado'],
	['Theodore Roosevelt National Park','Barcelona'],
	['Theodore Roosevelt National Park','Chicago'],
	['Theodore Roosevelt National Park','Murlough Bay'],
	['Theodore Roosevelt National Park','Pennybacker Bridge'],
	['Theodore Roosevelt National Park','Pumpkin Pie'],
	['Theodore Roosevelt National Park','Avocado'],
	['Theodore Roosevelt National Park','Barcelona'],
	['Toco Toucan','Goldendoodle'],
	['Toco Toucan','Hawaii'],
	['Toco Toucan','Los Angeles'],
	['Toco Toucan','Memphis'],
	['Toco Toucan','Nashville'],
	['Toco Toucan','Texas'],
	['Toco Toucan','Krakatoa'],
	['Toms River','Madrid'],
	['Tornado','Barcelona'],
	['Tornado','Broccoli'],
	['Tornado','Empire State Building'],
	['Tornado','Giraffe'],
	['Tornado','Goldendoodle'],
	['Tornado','Barcelona'],
	['Tornado','Broccoli'],
	['Tornado','Empire State Building'],
	['Tornado','Monarch Butterfly'],
	['Tornado','Empire State Building'],
	['Tornado','Monarch Butterfly'],
	['Triple Falls','Memphis'],
	['Triple Falls','New York'],
	['Triple Falls','Argania'],
	['Triple Falls','Dog'],
	['Trollstigen','Bald Eagle'],
	['Trollstigen','Cape Reinga'],
	['Trollstigen','Dance'],
	['Trollstigen','Giraffe'],
	['Trollstigen','Goldendoodle'],
	['Trollstigen','Ice Cream'],
	['Trollstigen','Manatee'],
	['Trollstigen','Rabbit'],
	['Trollstigen','Bald Eagle'],
	['Trollstigen','Drawing'],
	['Trollstigen','Zucchini'],
	['Tuscany','Bartolome Island'],
	['Tuscany','Castle Point Lighthouse'],
	['Tuscany','Dance'],
	['Tuscany','Drawing'],
	['Tuscany','Four Corners Monument Hurricane Katrina'],
	['Tuscany','Italy'],
	['Tuscany','Moon Hill'],
	['Tuscany','Murlough Bay'],
	['Tuscany','Palace of Westminster'],
	['Tuscany','Rabbit'],
	['Tuscany','Sea Otter'],
	['Tuscany','Toco Toucan'],
	['Tuscany','Triple Falls'],
	['Tuscany','White Cliffs of Dover'],
	['Tuscany','Avocado'],
	['Tuscany','Bald Eagle'],
	['Tuscany','Bartolome Island'],
	['Valley of Fire State Park','New York'],
	['Volcano','Bhumibol Bridge'],
	['Volcano','Hurricane Katrina'],
	['Volcano','Tablespoon'],
	['Volcano','Bhumibol Bridge'],
	['White Cliffs of Dover','Memphis'],
	['White Cliffs of Dover','Rabbit'],
	['White Cliffs of Dover','Recycling'],
	['White Cliffs of Dover','Tornado'],
	['White Cliffs of Dover','Volcano'],
	['Wildebeest','Cape Reinga'],
	['Wildebeest','Castle Point Lighthouse'],
	['Wildebeest','Fremont Peak'],
	['Wildebeest','Goldendoodle'],
	['Wildebeest','Grasslands National Park'],
	['Wildebeest','Honolulu'],
	['Wildebeest','Junk Food'],
	['Wildebeest','Ketogenic Diet'],
	['Wildebeest','Laem Son National Park'],
	['Wildebeest','Laguna Beach'],
	['Wildebeest','Lake of the Clouds'],
	['Wildebeest','Lighthouse'],
	['Wildebeest','Los Angeles'],
	['Wildebeest','Manatee'],
	['Wildebeest','Moon'],
	['Wildebeest','Pennybacker Bridge'],
	['Wildebeest','Tahquamenon River'],
	['Woolly Mammoth','Bartolome Island'],
	['Woolly Mammoth','Bearded Vulture'],
	['Woolly Mammoth','Bow Lake'],
	['Woolly Mammoth','Chicago'],
	['Woolly Mammoth','Giraffe'],
	['Woolly Mammoth','Honolulu'],
	['Woolly Mammoth','Laem Son National Park'],
	['Woolly Mammoth','Lighthouse'],
	['Woolly Mammoth','Los Angeles'],
	['Woolly Mammoth','Murlough Bay'],
	['Woolly Mammoth','Niagara Falls'],
	['Woolly Mammoth','Santa Catalina Island'],
	['Woolly Mammoth','Similan Islands'],
	['Woolly Mammoth','Snack'],
	['Woolly Mammoth','Amazon Rainforest'],
	['Woolly Mammoth','Bartolome Island'],
	['Woolly Mammoth','Bearded Vulture'],
	['Woolly Mammoth','Bow Lake'],
	['World Elephant Day','Amazon Rainforest'],
	['World Elephant Day','Bald Eagle'],
	['World Elephant Day','Bhumibol Bridge'],
	['World Elephant Day','Bow Lake'],
	['World Elephant Day','Caribbean'],
	['World Elephant Day','Chicago'],
	['World Elephant Day','Dance'],
	['World Elephant Day','Flamingo'],
	['World Elephant Day','Lake Geneva'],
	['World Elephant Day','Lake of the Clouds'],
	['World Elephant Day','Palace of Westminster'],
	['World Elephant Day','Pennybacker Bridge'],
	['World Elephant Day','Santa Catalina Island'],
	['World Elephant Day','Similan Islands'],
	['World Elephant Day','Tablespoon'],
	['World Elephant Day','Tahquamenon River'],
	['World Elephant Day','Texas'],
	['World Elephant Day','Amazon Rainforest'],
	['World Elephant Day','Bald Eagle'],
	['World Elephant Day','Bhumibol Bridge'],
	['World Elephant Day','Bow Lake'],
	['Zucchini','Bartolome Island'],
]

def getPairs():
	return Pairs

def main():	
	global UnsearchedLinks
	global SearchedLinks
	
	first = input('Enter first search term: ')
	second = input('Enter second search term: ')
	print("")
	
	firstWins = False
	secondWins = False
	
	if checkForMatch(first, second):
		firstWins = True
	elif findEndLink(second, 1):
		firstWins = True
		
	if checkForMatch(second, first):
		secondWins = True
	elif findEndLink(first, 2):
		secondWins = True
		
	if firstWins and secondWins:
		print('********************\n********************\nERROR: Winner could not be determined because both have been winners.\n********************\n********************\n')
	if firstWins:		
		print(first + " > " + second)
		printChain(first, second, 1)
	if secondWins:
		print(second + " > " + first)
		printChain(second, first, 2)	
	if not firstWins and not secondWins:
		print('No match could be found')
	
	return

def printChain(top, bottom, check):
	print("\nFull Chain:")
	chain = top
	if check == 1:
		for link in reversed(Chain1):
			chain += " > " + link
	elif check == 2:
		for link in reversed(Chain2):
			chain += " > " + link
	chain += " > " + bottom
	
	print(chain)
	print("")

def findEndLink(target, check):
	global UnsearchedLinks
	global SearchedLinks
	
	if not UnsearchedLinks:
		return False
	
	unsearchedLinksCopy = UnsearchedLinks
	UnsearchedLinks = []
	
	for link in unsearchedLinksCopy:
		if searchLink(link, target, check):
			return True
			
	return False

def searchLink(link, target, check):
	global SearchedLinks

	allPairs = getPairs()

	for pair in allPairs:
		if link == pair[0]:
			if target == pair[1]:
				if check == 1:
					Chain1.append(link)
				elif check == 2:
					Chain2.append(link)
				return True
			else:
				SearchedLinks.append(link)
				if pair[1] not in SearchedLinks:
					if searchLink(pair[1], target, check):
						if check == 1:
							Chain1.append(link)
						elif check == 2:
							Chain2.append(link)
						return True
	return False

def checkForMatch(first, second):
	global UnsearchedLinks
	global SearchedLinks
	
	SearchedLinks = []
	UnsearchedLinks = []
	allPairs = getPairs()

	for pair in allPairs:
		if first == pair[0]:
			if second == pair[1]:
				return True
			else:
				UnsearchedLinks.append(pair[1])
				
	return False

main()